#!/usr/bin/env python3
"""
Simple IoT sensor data simulator for OpenClaw-Lab
- Publishes to MQTT
- Also logs every message to the exact file your MQTT listener skill uses

Dependencies:
    pip install paho-mqtt numpy
"""

import json
import time
import random
import os
from datetime import datetime, timezone
import paho.mqtt.client as mqtt
import numpy as np

# ==================== CONFIG ====================

MQTT_BROKER = "localhost"
MQTT_PORT = 1883
MQTT_CLIENT_ID = f"simulator-{random.randint(1000,9999)}"

BASE_TOPIC = "/lab"

# Log file path — matches your skill's location
HOME = os.path.expanduser("~")  # gets /home/node or current user's home
LOG_DIR = os.path.join(HOME, ".openclaw/workspace/skills/mqtt-lab-listener/workspace/daily")


os.makedirs(LOG_DIR, exist_ok=True)

def get_log_filename():
    today = datetime.now(timezone.utc).strftime("%Y-%m-%d")
    return os.path.join(LOG_DIR, f"{today}-mqtt.log")

# Devices (same as before)
DEVICES = [
    {
        "id": "dev-001-labA",
        "location": "Lab A - Shelf 3",
        "sensors": ["temperature", "humidity"],
        "temp_base": 23.5,
        "temp_noise": 0.4,
        "humidity_base": 52.0,
        "humidity_noise": 3.5,
        "publish_interval": (8, 18),
    },
    {
        "id": "dev-002-labB",
        "location": "Lab B - Chemical bench",
        "sensors": ["pH", "conductivity"],
        "ph_base": 7.1,
        "ph_noise": 0.08,
        "conductivity_base": 2.4,
        "conductivity_noise": 0.3,
        "publish_interval": (12, 35),
    },
    {
        "id": "dev-003-labC",
        "location": "Incubator",
        "sensors": ["temperature"],
        "temp_base": 37.0,
        "temp_noise": 0.15,
        "publish_interval": (15, 25),
    }
]

SIM_START_TIME = time.time()
ENABLE_JUMPS = True
ENABLE_OUTAGES = True
ENABLE_DRIFT = True

# ==================== HELPERS ====================

def get_iso_timestamp():
    return datetime.now(timezone.utc).isoformat(timespec='milliseconds') + "Z"

def add_realistic_noise(base, noise_level, drift=0.0):
    noise = np.random.normal(0, noise_level)
    return round(base + noise + drift, 2)

def maybe_jump(value, sensor_type):
    if not ENABLE_JUMPS:
        return value
    if random.random() < 0.008:
        direction = random.choice([-1, 1])
        magnitude = random.uniform(2.5, 6.0)
        if sensor_type == "temperature":
            magnitude *= 1.2
        elif sensor_type == "pH":
            magnitude *= 0.4
        print(f"   → Sudden jump! {sensor_type} {direction*magnitude:+.1f}")
        return value + direction * magnitude
    return value

def get_drift_factor(elapsed_hours):
    if not ENABLE_DRIFT:
        return 0.0
    drift_rate = random.uniform(-0.10, 0.10) / 3600
    return drift_rate * elapsed_hours * 3600

def simulate_outage():
    if ENABLE_OUTAGES and random.random() < 0.004:
        duration_sec = random.randint(120, 600)
        print(f"   !!! Outage simulation: sleeping {duration_sec}s ...")
        time.sleep(duration_sec)

def log_to_file(topic, payload_dict):
    log_entry = {
        "timestamp": get_iso_timestamp(),
        "topic": topic,
        "message": json.dumps(payload_dict),           # raw JSON string
        "struct_redacted": False,
        "anomaly_scored": False
    }
    log_path = get_log_filename()
    with open(log_path, "a", encoding="utf-8") as f:
        f.write(json.dumps(log_entry) + "\n")

# ==================== PUBLISH + LOG ====================

def publish_message(client, device, sensor_type, value, unit):
    topic = f"{BASE_TOPIC}/{device['id']}/{sensor_type}"
    payload = {
        "device_id": device["id"],
        "sensor_type": sensor_type,
        "value": value,
        "unit": unit,
        "ts": get_iso_timestamp(),
        "location": device["location"],
        "sim_note": "generated by sensor-data-generator.py"
    }
    payload_str = json.dumps(payload)

    # Publish to MQTT
    try:
        result = client.publish(topic, payload_str, qos=1)
        if result.rc == mqtt.MQTT_ERR_SUCCESS:
            print(f"Published → {topic:<35}  {value:>6} {unit}")
        else:
            print(f"Publish failed (rc={result.rc})")
    except Exception as e:
        print(f"Publish error: {e}")

    # Log to the file your skill expects
    log_to_file(topic, payload)

# ==================== MAIN LOOP ====================

def main():
    client = mqtt.Client(client_id=MQTT_CLIENT_ID, clean_session=True)
    client.connect(MQTT_BROKER, MQTT_PORT, 60)
    client.loop_start()

    print(f"Simulator started → broker={MQTT_BROKER}:{MQTT_PORT}")
    print(f"Logging also to: {get_log_filename()}")
    print("Publishing to /lab/# ...  Ctrl+C to stop\n")

    last_publish = {d["id"]: {} for d in DEVICES}

    try:
        while True:
            now = time.time()
            elapsed_hours = (now - SIM_START_TIME) / 3600.0

            for device in DEVICES:
                for sensor in device["sensors"]:
                    key = f"{device['id']}_{sensor}"

                    if key not in last_publish[device["id"]]:
                        last_publish[device["id"]][sensor] = now - 60

                    last_time = last_publish[device["id"]][sensor]
                    min_int, max_int = device.get("publish_interval", (10, 20))
                    next_interval = random.uniform(min_int, max_int)

                    if now - last_time >= next_interval:
                        simulate_outage()

                        if sensor == "temperature":
                            base = device["temp_base"]
                            noise = device["temp_noise"]
                            unit = "°C"
                        elif sensor == "humidity":
                            base = device["humidity_base"]
                            noise = device["humidity_noise"]
                            unit = "%"
                        elif sensor == "pH":
                            base = device["ph_base"]
                            noise = device["ph_noise"]
                            unit = "pH"
                        elif sensor == "conductivity":
                            base = device["conductivity_base"]
                            noise = device["conductivity_noise"]
                            unit = "mS/cm"
                        else:
                            continue

                        drift = get_drift_factor(elapsed_hours)
                        value = add_realistic_noise(base, noise, drift)
                        value = maybe_jump(value, sensor)

                        publish_message(client, device, sensor, value, unit)

                        last_publish[device["id"]][sensor] = now

            time.sleep(0.5)

    except KeyboardInterrupt:
        print("\nStopped by user.")
    finally:
        client.loop_stop()
        client.disconnect()
        print("MQTT client disconnected.")

if __name__ == "__main__":
    main()